"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  Container,
  PageMasthead,
  Section,
  Split,
  ListRow,
  GroupHeading,
  MetaList,
} from "@/components/layout";
import { EmptyState } from "@/components/app/EmptyState";
import { FilterStrip } from "@/components/app/FilterStrip";
import { DataTable } from "@/components/app/DataTable";
import { Mark, VerificationTag } from "@/components/shared";
import { Label } from "@/components/type";
import { Button } from "@/components/ui/button";
import { GENERATED_ITEM } from "@/fixtures/content/generated-item";
import { GENERATION_RUN, type BatchQuestion } from "@/fixtures/content/generation-run";
import { getStudent } from "@/fixtures/students";

const MAP_LABEL: Record<string, string> = {
  NONE: "Correct answer",
  M1: "M1 · grams as moles",
  M2: "M2 · ignores coefficients",
  M3: "M3 · inverts the ratio",
  unmapped: "Unmapped",
};

const BATCH_MAP_LABEL: Record<string, string> = {
  NONE: "Correct answer",
  M4: "M4 · reads one place too far right",
  unmapped: "Unmapped",
};

type Verdict = "approve" | "edit" | "reject";
type Tab = "separator" | "batch";

export default function ContentReviewQueue() {
  const router = useRouter();
  const item = GENERATED_ITEM;
  const run = GENERATION_RUN;

  const [tab, setTab] = useState<Tab>("separator");
  const [separatorRejected, setSeparatorRejected] = useState(false);
  const [verdicts, setVerdicts] = useState<Record<string, Verdict>>({});
  const [selectedId, setSelectedId] = useState<string>(
    run.finalBatch[0]?.id ?? "",
  );

  const tally = useMemo(() => {
    const values = Object.values(verdicts);
    return {
      approved: values.filter((v) => v === "approve").length,
      edited: values.filter((v) => v === "edit").length,
      rejected: values.filter((v) => v === "reject").length,
    };
  }, [verdicts]);
  const committable = tally.approved + tally.edited;
  const selected = run.finalBatch.find((q) => q.id === selectedId);

  function setVerdict(id: string, v: Verdict) {
    setVerdicts((s) => ({ ...s, [id]: v }));
  }

  function commit() {
    toast.success(`${committable} items sent for a second reviewer`, {
      description: `Batch ${run.id}: ${tally.approved} approved, ${tally.edited} approved with an edit, ${tally.rejected} rejected.`,
    });
    router.push(`/teacher/content-review/agreement?batch=${run.id}`);
  }

  return (
    <Container width="wide">
      <PageMasthead
        label="Content review"
        title="Content review queue"
        lede="Nothing here goes live on its own. Approve, and it moves to a second reviewer before entering the bank."
        tabs={
          <FilterStrip
            label="Review sections"
            value={tab}
            onChange={setTab}
            options={[
              { value: "separator", label: "Separator item" },
              { value: "batch", label: `Batch of ${run.finalBatch.length}` },
            ]}
          />
        }
      />

      {tab === "separator" ? (
        <Section size="tight">
          {!separatorRejected ? (
            <div className="max-w-3xl">
              <MetaList
                items={[
                  { label: "ID", value: item.id },
                  { label: "Created", value: item.createdAt },
                  { label: "Generated by", value: item.generatedBy },
                ]}
              />

              <p className="mt-10 text-base leading-relaxed text-muted-foreground">
                Generated to close a gap: no question separated{" "}
                <strong className="text-foreground">{item.gap.labels[0]}</strong> from{" "}
                <strong className="text-foreground">{item.gap.labels[1]}</strong>.
                Detected {item.gap.detectedAt} from {item.gap.detectedFrom}.
              </p>

              <Label tone="muted" className="mt-10">
                Generated question
              </Label>
              <p className="mt-4 text-2xl font-semibold leading-snug tracking-tight">
                {item.question}
              </p>

              <OptionsTable
                options={item.options}
                mapLabel={(m) => MAP_LABEL[m] ?? m}
              />

              <div className="mt-8 flex flex-wrap gap-8">
                <span className="flex items-center gap-3 text-sm">
                  Distractor values
                  <VerificationTag kind={item.distractorSource} />
                </span>
                <span className="flex items-center gap-3 text-sm">
                  Misconception mapping
                  <VerificationTag kind={item.mappingSource} />
                </span>
              </div>

              <div className="mt-12 flex flex-wrap gap-8">
                <Button
                  onClick={() => router.push("/teacher/content-review/agreement")}
                >
                  Approve and send to second reviewer
                </Button>
                <Button
                  variant="outline"
                  onClick={() =>
                    toast("Editor not in this build", {
                      description: "You'd adjust the question text or a mapping here.",
                    })
                  }
                >
                  Edit
                </Button>
                <Button variant="outline" onClick={() => setSeparatorRejected(true)}>
                  Reject
                </Button>
              </div>
            </div>
          ) : (
            <EmptyState
              title="Returned to the generator"
              body="The item was rejected. Nothing else is waiting in this section."
            />
          )}
        </Section>
      ) : (
        <Section size="tight">
          <Split
            ratio="8/4"
            sticky
            primary={
              <div>
                <GroupHeading count={run.finalBatch.length}>
                  {getStudent(run.trigger.studentId)?.name ?? "A student"}
                </GroupHeading>
                <div className="border-t border-border">
                  {run.finalBatch.map((q) => (
                    <ListRow
                      key={q.id}
                      title={q.questionText}
                      meta={`Scorer ${q.score.toFixed(2)}${
                        verdicts[q.id]
                          ? ` · ${
                              verdicts[q.id] === "approve"
                                ? "Approved"
                                : verdicts[q.id] === "edit"
                                  ? "Approved (edited)"
                                  : "Rejected"
                            }`
                          : ""
                      }`}
                      selected={q.id === selectedId}
                      onSelect={() => setSelectedId(q.id)}
                    />
                  ))}
                </div>
                <div className="mt-10 flex flex-wrap items-center justify-between gap-8">
                  <p className="text-sm text-muted-foreground">
                    <span className="nums font-medium text-foreground">{committable}</span>{" "}
                    items ready
                  </p>
                  <Button onClick={commit} disabled={committable === 0}>
                    Send
                  </Button>
                </div>
              </div>
            }
            secondary={
              selected ? (
                <BatchDetail
                  question={selected}
                  verdict={verdicts[selected.id]}
                  onVerdict={(v) => setVerdict(selected.id, v)}
                />
              ) : undefined
            }
          />
        </Section>
      )}
    </Container>
  );
}

function BatchDetail({
  question,
  verdict,
  onVerdict,
}: {
  question: BatchQuestion;
  verdict: Verdict | undefined;
  onVerdict: (v: Verdict) => void;
}) {
  return (
    <div>
      <p className="text-xl font-semibold leading-snug tracking-tight">
        {question.questionText}
      </p>

      <OptionsTable
        options={question.options}
        mapLabel={(m) => BATCH_MAP_LABEL[m] ?? m}
      />

      <div className="mt-8 flex flex-wrap gap-8 text-sm">
        <span>
          Scorer rating{" "}
          <span className="nums font-medium">{question.score.toFixed(2)}</span>
        </span>
        <span className="flex items-center gap-3">
          Answer <VerificationTag kind="computed" />
        </span>
        {verdict ? (
          <Mark
            bucket={verdict === "reject" ? "attention" : "confirmed"}
          >
            {verdict === "approve"
              ? "Approved"
              : verdict === "edit"
                ? "Approved (edited)"
                : "Rejected"}
          </Mark>
        ) : null}
      </div>

      <div className="mt-10 flex flex-wrap gap-8">
        <Button onClick={() => onVerdict("approve")}>Approve</Button>
        <Button
          variant="outline"
          onClick={() => {
            onVerdict("edit");
            toast("Editor not in this build", {
              description: "You'd adjust the question text or a mapping here.",
            });
          }}
        >
          Edit
        </Button>
        <Button variant="outline" onClick={() => onVerdict("reject")}>
          Reject
        </Button>
      </div>
    </div>
  );
}

function OptionsTable({
  options,
  mapLabel,
}: {
  options: { text: string; maps: string; rationale: string; correct?: boolean }[];
  mapLabel: (maps: string) => string;
}) {
  return (
    <DataTable
      className="mt-10"
      caption="Options"
      getRowKey={(o) => o.text}
      rows={options}
      columns={[
        {
          key: "option",
          header: "Option",
          cell: (o) => (
            <span className="font-medium">
              {o.text}
              {o.correct ? <span className="label ml-3 text-accent">correct</span> : null}
            </span>
          ),
        },
        {
          key: "maps",
          header: "Maps to",
          className: "text-muted-foreground",
          cell: (o) => mapLabel(o.maps),
        },
        {
          key: "why",
          header: "Why",
          className: "text-muted-foreground",
          cell: (o) => o.rationale,
        },
      ]}
    />
  );
}
