import { PageShell } from "@/components/app/PageShell";
import { Surface } from "@/components/app/primitives";
import { AdminTabs } from "../Tabs";
import { PROVENANCE_LOG, type ProvenanceEntry } from "@/fixtures/provenance";
import { cn } from "@/lib/utils";

const KIND_LABEL: Record<ProvenanceEntry["kind"], string> = {
  question: "Question",
  "distractor-set": "Distractor set",
  "consultant-suggestion": "Consultant suggestion",
  "generation-run": "Generation run",
};

const STATUS_STYLE: Record<ProvenanceEntry["status"], string> = {
  "in-bank": "border-ok/30 bg-ok/10 text-ok",
  "in-review": "border-info/30 bg-info/10 text-info",
  rejected: "border-warn/40 bg-warn/10 text-warn-foreground dark:text-warn",
  surfaced: "border-border bg-muted text-muted-foreground",
};

export default function ProvenanceLog() {
  return (
    <PageShell
      title="Generation provenance log"
      description="Every AI-generated question or suggestion, with when it was created, what generated it, and who validated it."
      tabs={<AdminTabs />}
      wide
    >
      <div className="space-y-3">
        {PROVENANCE_LOG.map((e) => (
          <Surface key={e.id} className="p-4">
            <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
              <span className="rounded bg-muted px-1.5 py-0.5 font-mono">
                {e.id}
              </span>
              <span className="font-medium text-foreground">
                {KIND_LABEL[e.kind]}
              </span>
              <span>·</span>
              <span>{e.subject}</span>
              <span
                className={cn(
                  "ml-auto rounded-full border px-2 py-0.5 font-medium",
                  STATUS_STYLE[e.status],
                )}
              >
                {e.status}
              </span>
            </div>
            <p className="mt-2 text-sm">{e.purpose}</p>
            <dl className="mt-3 grid gap-x-6 gap-y-1 text-xs text-muted-foreground sm:grid-cols-2">
              <div className="flex gap-1.5">
                <dt className="font-medium">Created</dt>
                <dd>{e.createdOn}</dd>
              </div>
              <div className="flex gap-1.5">
                <dt className="font-medium">Generated by</dt>
                <dd>{e.generatedBy}</dd>
              </div>
              <div className="flex gap-1.5 sm:col-span-2">
                <dt className="font-medium">Validated by</dt>
                <dd>{e.validators.join(", ")}</dd>
              </div>
            </dl>
            {e.note ? (
              <p className="mt-2 border-t border-border pt-2 text-xs text-muted-foreground">
                {e.note}
              </p>
            ) : null}
          </Surface>
        ))}
      </div>
    </PageShell>
  );
}
