"use client";

import { useMemo, useState } from "react";
import {
  Container,
  PageMasthead,
  Section,
  Split,
  MetaList,
} from "@/components/layout";
import { DataTable } from "@/components/app/DataTable";
import { FilterStrip } from "@/components/app/FilterStrip";
import { Mark } from "@/components/shared";
import { Label } from "@/components/type";
import { PROVENANCE_LOG, type ProvenanceEntry } from "@/fixtures/provenance";

const KIND_LABEL: Record<ProvenanceEntry["kind"], string> = {
  question: "Question",
  "distractor-set": "Distractor set",
  "consultant-suggestion": "Consultant suggestion",
  "generation-run": "Generation run",
};

const STATUS_BUCKET: Record<
  ProvenanceEntry["status"],
  "confirmed" | "pending" | "attention" | "inert"
> = {
  "in-bank": "confirmed",
  "in-review": "pending",
  rejected: "inert",
  surfaced: "inert",
};

const STATUS_LABEL: Record<ProvenanceEntry["status"], string> = {
  "in-bank": "In bank",
  "in-review": "In review",
  rejected: "Rejected",
  surfaced: "Surfaced",
};

type Filter = "all" | ProvenanceEntry["status"];

export default function ProvenanceLog() {
  const [filter, setFilter] = useState<Filter>("all");
  const [selectedId, setSelectedId] = useState(PROVENANCE_LOG[0]?.id ?? "");

  const rows = useMemo(
    () =>
      filter === "all"
        ? PROVENANCE_LOG
        : PROVENANCE_LOG.filter((e) => e.status === filter),
    [filter],
  );

  const selected =
    rows.find((e) => e.id === selectedId) ??
    PROVENANCE_LOG.find((e) => e.id === selectedId) ??
    rows[0];

  const counts = {
    all: PROVENANCE_LOG.length,
    "in-bank": PROVENANCE_LOG.filter((e) => e.status === "in-bank").length,
    "in-review": PROVENANCE_LOG.filter((e) => e.status === "in-review").length,
    rejected: PROVENANCE_LOG.filter((e) => e.status === "rejected").length,
    surfaced: PROVENANCE_LOG.filter((e) => e.status === "surfaced").length,
  };

  return (
    <Container width="wide">
      <PageMasthead
        label="Provenance"
        title="Generation provenance log"
        lede="Every AI-generated question or suggestion, with when it was created, what generated it, and who validated it."
      />

      <div className="sticky top-[var(--topbar-h)] z-20 border-b border-border bg-background">
        <FilterStrip
          label="Filter by status"
          value={filter}
          onChange={setFilter}
          options={[
            { value: "all", label: "All", count: counts.all },
            { value: "in-bank", label: "In bank", count: counts["in-bank"] },
            { value: "in-review", label: "In review", count: counts["in-review"] },
            { value: "rejected", label: "Rejected", count: counts.rejected },
            { value: "surfaced", label: "Surfaced", count: counts.surfaced },
          ]}
        />
      </div>

      <Section size="tight">
        <Split
          ratio="8/4"
          sticky
          primary={
            <DataTable
              caption="Provenance entries"
              rows={rows}
              getRowKey={(e) => e.id}
              onRowClick={(e) => setSelectedId(e.id)}
              isRowSelected={(e) => e.id === selected?.id}
              columns={[
                {
                  key: "id",
                  header: "ID",
                  className: "font-mono text-xs",
                  cell: (e) => e.id,
                },
                {
                  key: "kind",
                  header: "Kind",
                  cell: (e) => KIND_LABEL[e.kind],
                },
                {
                  key: "subject",
                  header: "Subject",
                  className: "capitalize",
                  cell: (e) => e.subject,
                },
                {
                  key: "created",
                  header: "Created",
                  className: "whitespace-nowrap text-muted-foreground",
                  cell: (e) => e.createdOn,
                },
                {
                  key: "by",
                  header: "Generated by",
                  className: "text-muted-foreground",
                  cell: (e) => e.generatedBy,
                },
                {
                  key: "status",
                  header: "Status",
                  cell: (e) => (
                    <Mark bucket={STATUS_BUCKET[e.status]}>{STATUS_LABEL[e.status]}</Mark>
                  ),
                },
              ]}
            />
          }
          secondary={
            selected ? (
              <div>
                <Label tone="muted">{selected.id}</Label>
                <h2 className="mt-4 text-2xl font-semibold tracking-tight">
                  {KIND_LABEL[selected.kind]}
                </h2>
                <p className="mt-6 text-base leading-relaxed">{selected.purpose}</p>
                <MetaList
                  className="mt-10"
                  items={[
                    { label: "Validated by", value: selected.validators.join(", ") },
                    { label: "Created", value: selected.createdOn },
                    { label: "Generated by", value: selected.generatedBy },
                    {
                      label: "Status",
                      value: (
                        <Mark bucket={STATUS_BUCKET[selected.status]}>
                          {STATUS_LABEL[selected.status]}
                        </Mark>
                      ),
                    },
                  ]}
                />
                {selected.note ? (
                  <p className="mt-8 text-sm text-muted-foreground">{selected.note}</p>
                ) : null}
              </div>
            ) : null
          }
        />
      </Section>
    </Container>
  );
}
